/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Reference = IDL.Record({
  'name' : IDL.Text,
  'reference' : ExternalBlob,
});
export const Logo = IDL.Record({ 'logo' : ExternalBlob, 'name' : IDL.Text });
export const Color = IDL.Record({ 'hex' : IDL.Text, 'name' : IDL.Text });
export const BrandKit = IDL.Record({
  'references' : IDL.Vec(Reference),
  'logo' : IDL.Opt(Logo),
  'name' : IDL.Text,
  'colors' : IDL.Vec(Color),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkBrandKitExists' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'clearColors' : IDL.Func([], [], []),
  'clearLogo' : IDL.Func([], [], []),
  'clearReferences' : IDL.Func([], [], []),
  'getBrandKit' : IDL.Func([IDL.Principal], [IDL.Opt(BrandKit)], ['query']),
  'getCallerBrandKit' : IDL.Func([], [IDL.Opt(BrandKit)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerBrandKit' : IDL.Func([BrandKit], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Reference = IDL.Record({
    'name' : IDL.Text,
    'reference' : ExternalBlob,
  });
  const Logo = IDL.Record({ 'logo' : ExternalBlob, 'name' : IDL.Text });
  const Color = IDL.Record({ 'hex' : IDL.Text, 'name' : IDL.Text });
  const BrandKit = IDL.Record({
    'references' : IDL.Vec(Reference),
    'logo' : IDL.Opt(Logo),
    'name' : IDL.Text,
    'colors' : IDL.Vec(Color),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkBrandKitExists' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'clearColors' : IDL.Func([], [], []),
    'clearLogo' : IDL.Func([], [], []),
    'clearReferences' : IDL.Func([], [], []),
    'getBrandKit' : IDL.Func([IDL.Principal], [IDL.Opt(BrandKit)], ['query']),
    'getCallerBrandKit' : IDL.Func([], [IDL.Opt(BrandKit)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerBrandKit' : IDL.Func([BrandKit], [], []),
  });
};

export const init = ({ IDL }) => { return []; };